project_id = "fzgjmvxtgrlwrluxdwjq"

[functions.r2-upload]
verify_jwt = false

[functions.angel-voice-elevenlabs]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.angel-chat]
verify_jwt = false

[functions.angel-voice]
verify_jwt = false
